# Generated by Django 6.0.2 on 2026-02-20 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insight',
            options={'ordering': ['-year']},
        ),
        migrations.AddField(
            model_name='insight',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insight',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
